package com.example.data.repository

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Environment
import androidx.core.content.FileProvider
import com.example.data.model.HifzPlan
import com.example.data.model.HifzProgress
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object HifzExporter {

    fun generateTextReport(
        plans: List<HifzPlan>,
        allProgress: List<HifzProgress>,
        isEnglish: Boolean
    ): String {
        val totalMemorized = plans.sumOf { maxOf(0, it.currentProgressAyah - it.startAyah + 1) }
        val masteredCount = allProgress.count { it.status == 2 }
        val underReviewCount = allProgress.count { it.status == 1 }
        val dateStr = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date())

        val sb = StringBuilder()
        if (isEnglish) {
            sb.appendLine("=========================================")
            sb.appendLine("   QURAN HIFZ & MEMORIZATION REPORT   ")
            sb.appendLine("=========================================")
            sb.appendLine("Export Date: $dateStr")
            sb.appendLine()
            sb.appendLine("--- OVERALL STATISTICS ---")
            sb.appendLine("• Total Verses Memorized: $totalMemorized")
            sb.appendLine("• Mastered Verses (Green): $masteredCount")
            sb.appendLine("• Verses Under Review (Yellow): $underReviewCount")
            sb.appendLine("• Total Active Hifz Plans: ${plans.size}")
            sb.appendLine()
            sb.appendLine("--- ACTIVE HIFZ PLANS ---")
            if (plans.isEmpty()) {
                sb.appendLine("No active plans created yet.")
            } else {
                plans.forEachIndexed { i, plan ->
                    val completionPercent = if (plan.endAyah >= plan.startAyah) {
                        val total = plan.endAyah - plan.startAyah + 1
                        val current = maxOf(0, plan.currentProgressAyah - plan.startAyah + 1)
                        (current * 100) / total
                    } else 0
                    sb.appendLine("${i + 1}. ${plan.title}")
                    sb.appendLine("   - Surah: ${plan.surahName} (Ayahs ${plan.startAyah} - ${plan.endAyah})")
                    sb.appendLine("   - Current Ayah: ${plan.currentProgressAyah} ($completionPercent% completed)")
                    sb.appendLine("   - Daily Goal Pace: ${plan.dailyAyahsCount} ayahs/day")
                    sb.appendLine()
                }
            }
            sb.appendLine("=========================================")
            sb.appendLine("Generated by Quran App - AI Studio")
        } else {
            sb.appendLine("=========================================")
            sb.appendLine("    تقرير إنجازات حفظ القرآن الكريم    ")
            sb.appendLine("=========================================")
            sb.appendLine("تاريخ التصدير: $dateStr")
            sb.appendLine()
            sb.appendLine("--- ملخص الإحصائيات العامة ---")
            sb.appendLine("• إجمالي الآيات المحفوظة: $totalMemorized آية")
            sb.appendLine("• الآيات المتقنة (🟢): $masteredCount آية")
            sb.appendLine("• الآيات قيد المراجعة (🟡): $underReviewCount آية")
            sb.appendLine("• عدد خطط الحفظ النشطة: ${plans.size}")
            sb.appendLine()
            sb.appendLine("--- تفاصيل خطط الحفظ ---")
            if (plans.isEmpty()) {
                sb.appendLine("لا توجد خطط حفظ نشطة حالياً.")
            } else {
                plans.forEachIndexed { i, plan ->
                    val completionPercent = if (plan.endAyah >= plan.startAyah) {
                        val total = plan.endAyah - plan.startAyah + 1
                        val current = maxOf(0, plan.currentProgressAyah - plan.startAyah + 1)
                        (current * 100) / total
                    } else 0
                    sb.appendLine("${i + 1}. الخطة: ${plan.title}")
                    sb.appendLine("   - السورة: ${plan.surahName} (الآيات ${plan.startAyah} إلى ${plan.endAyah})")
                    sb.appendLine("   - التقدم الحالي: الوصول للآية ${plan.currentProgressAyah} (تم إنجاز $completionPercent%)")
                    sb.appendLine("   - المقدار اليومي: ${plan.dailyAyahsCount} آيات/يوم")
                    sb.appendLine()
                }
            }
            sb.appendLine("=========================================")
            sb.appendLine("تطوير تطبيق القرآن الكريم - AI Studio")
        }
        return sb.toString()
    }

    fun exportPdfReport(
        context: Context,
        plans: List<HifzPlan>,
        allProgress: List<HifzProgress>,
        isEnglish: Boolean
    ): File? {
        val totalMemorized = plans.sumOf { maxOf(0, it.currentProgressAyah - it.startAyah + 1) }
        val masteredCount = allProgress.count { it.status == 2 }
        val underReviewCount = allProgress.count { it.status == 1 }
        val dateStr = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date())

        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 page size
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        // Background / Header Bar
        paint.color = Color.parseColor("#104E35") // Deep Islamic Green
        canvas.drawRect(0f, 0f, 595f, 90f, paint)

        // Header Title
        paint.color = Color.WHITE
        paint.textSize = 18f
        paint.isFakeBoldText = true
        val titleText = if (isEnglish) "QURAN HIFZ & MEMORIZATION REPORT" else "تقرير إنجازات حفظ القرآن الكريم وتتبّع المراجعة"
        canvas.drawText(titleText, 30f, 50f, paint)

        // Subtitle / Date
        paint.textSize = 10f
        paint.isFakeBoldText = false
        canvas.drawText(if (isEnglish) "Date: $dateStr" else "تاريخ التصدير: $dateStr", 30f, 72f, paint)

        // Content Area Start
        var yPos = 130f

        // Stats Cards Background Box
        paint.color = Color.parseColor("#F3F7F5")
        canvas.drawRoundRect(30f, yPos, 565f, yPos + 100f, 12f, 12f, paint)

        // Stats Content
        paint.color = Color.parseColor("#104E35")
        paint.textSize = 12f
        paint.isFakeBoldText = true
        canvas.drawText(if (isEnglish) "STATISTICS OVERVIEW" else "ملخص إحصائيات الحفظ والمراجعة", 45f, yPos + 25f, paint)

        paint.color = Color.DKGRAY
        paint.textSize = 11f
        paint.isFakeBoldText = false
        canvas.drawText(if (isEnglish) "• Verses Memorized: $totalMemorized" else "• إجمالي الآيات المحفوظة: $totalMemorized آية", 45f, yPos + 48f, paint)
        canvas.drawText(if (isEnglish) "• Mastered (Green): $masteredCount" else "• الآيات المتقنة (🟢): $masteredCount آية", 45f, yPos + 66f, paint)
        canvas.drawText(if (isEnglish) "• Under Review (Yellow): $underReviewCount" else "• الآيات قيد المراجعة (🟡): $underReviewCount آية", 45f, yPos + 84f, paint)

        yPos += 130f

        // Plans Section Header
        paint.color = Color.parseColor("#104E35")
        paint.textSize = 13f
        paint.isFakeBoldText = true
        canvas.drawText(if (isEnglish) "ACTIVE HIFZ PLANS (${plans.size})" else "تفاصيل خطط الحفظ النشطة (${plans.size})", 30f, yPos, paint)

        yPos += 20f

        if (plans.isEmpty()) {
            paint.color = Color.GRAY
            paint.textSize = 11f
            paint.isFakeBoldText = false
            canvas.drawText(if (isEnglish) "No active plans available." else "لا توجد خطط حفظ نشطة حالياً.", 30f, yPos, paint)
        } else {
            plans.take(10).forEachIndexed { index, plan ->
                val completionPercent = if (plan.endAyah >= plan.startAyah) {
                    val total = plan.endAyah - plan.startAyah + 1
                    val current = maxOf(0, plan.currentProgressAyah - plan.startAyah + 1)
                    (current * 100) / total
                } else 0

                paint.color = Color.parseColor("#FFFFFF")
                canvas.drawRoundRect(30f, yPos, 565f, yPos + 55f, 8f, 8f, paint)

                paint.color = Color.parseColor("#E0ECE6")
                paint.style = Paint.Style.STROKE
                paint.strokeWidth = 1f
                canvas.drawRoundRect(30f, yPos, 565f, yPos + 55f, 8f, 8f, paint)
                paint.style = Paint.Style.FILL

                paint.color = Color.BLACK
                paint.textSize = 11f
                paint.isFakeBoldText = true
                canvas.drawText("${index + 1}. ${plan.title}", 40f, yPos + 22f, paint)

                paint.color = Color.DKGRAY
                paint.textSize = 10f
                paint.isFakeBoldText = false
                val planDetails = if (isEnglish) {
                    "Surah: ${plan.surahName} | Ayahs ${plan.startAyah}-${plan.endAyah} | Progress: Ayah ${plan.currentProgressAyah} ($completionPercent%) | Target: ${plan.dailyAyahsCount}/day"
                } else {
                    "السورة: ${plan.surahName} | الآيات ${plan.startAyah}-${plan.endAyah} | التقدم: الآية ${plan.currentProgressAyah} ($completionPercent%) | المقدار: ${plan.dailyAyahsCount}/يوم"
                }
                canvas.drawText(planDetails, 40f, yPos + 40f, paint)

                yPos += 68f
            }
        }

        // Footer
        paint.color = Color.GRAY
        paint.textSize = 9f
        canvas.drawText("Generated by Quran AI App - Backup & Achievements Report", 30f, 810f, paint)

        pdfDocument.finishPage(page)

        return try {
            val file = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "quran_hifz_report_${System.currentTimeMillis()}.pdf")
            file.outputStream().use { pdfDocument.writeTo(it) }
            pdfDocument.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }

    fun shareTextReport(context: Context, text: String, isEnglish: Boolean) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, text)
        }
        val chooser = Intent.createChooser(intent, if (isEnglish) "Share Hifz Report" else "مشاركة تقرير الإنجاز والتسجيلات")
        context.startActivity(chooser)
    }

    fun sharePdfReport(context: Context, pdfFile: File, isEnglish: Boolean) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", pdfFile)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        val chooser = Intent.createChooser(intent, if (isEnglish) "Share Hifz PDF Report" else "مشاركة تقرير الحفظ بصيغة PDF")
        context.startActivity(chooser)
    }
}
